/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.sliit.iblood.view_controller;

import lk.sliit.iblood.common.OptionPane;
import lk.sliit.iblood.common.strings.Strings;

import javax.swing.*;
import java.awt.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * @author pandu
 */
public class MainMenu extends javax.swing.JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBloodGroup;
    private javax.swing.JToggleButton btnDoctor;
    private javax.swing.JToggleButton btnDonation;
    private javax.swing.JToggleButton btnDonor;
    private javax.swing.JToggleButton btnNurse;
    private javax.swing.JToggleButton btnRecipient;
    private javax.swing.ButtonGroup groupMenuButton;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel lblTitle;
    private lk.sliit.iblood.view_controller.BloodPanel pnlBloodDonation;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlRoot;
    // End of variables declaration//GEN-END:variables
    private JPanel currentPnl;
    private ContentType currentContent;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        OptionPane.init(this);
        initComponents();
        initTimer();
        setLocationRelativeTo(null);
        setTitle("iBlood - Main Menu");
        groupMenuButton.clearSelection();
        currentContent = ContentType.DONATION;
    }


    private void initTimer() {
        final DateFormat timeFormat = new SimpleDateFormat("E, MMM dd yyyy | HH:mm:ss");
        Timer timer = new Timer(1000, e -> {
            Date date = new Date();
            String time = timeFormat.format(date);
            lblTimer.setText(time);
        });
        // to make sure it doesn't wait one second at the start
        timer.setInitialDelay(0);
        timer.start();
    }
    private boolean isFistTime = true;

    private void switchToContent(ContentType contentType) {
        if (isFistTime || !(currentContent == contentType)
//                && OptionPane.confirmAsWarning(Strings.ASK_WHEN_QUIT_FROM_CONTENT) == OptionPane.YES
                ){
            switch (contentType) {
                case DONOR:
                    openInJFrame(new DonorPanel());
                    break;
                case RECIPIENT:
                    openInJFrame(new PatientPanel());
                    break;
                case DONATION:
                    openInJFrame(new BloodPanel());
                    break;
                case DOCTOR:
                    openInJFrame(new DoctorPanel());
                    break;
                case NURSE:
                    openInJFrame(new NursePanel());
                    break;
                case BLOOD_TYPE:
                    openInJFrame(new BloodGroupPanel());
                    break;
            }
            currentContent = contentType;
        }
    }
    private void openInJFrame(JPanel pnl){
        JFrame jFrame = new JFrame();
        jFrame.add(pnl);
        jFrame.setLocationRelativeTo(this);
        jFrame.pack();
        jFrame.setVisible(true);
        jFrame.setTitle(Strings.getString(Strings.OPTION_PANE_TITLE));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupMenuButton = new javax.swing.ButtonGroup();
        pnlBloodDonation = new lk.sliit.iblood.view_controller.BloodPanel();
        pnlRoot = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        btnRecipient = new javax.swing.JToggleButton();
        btnDonation = new javax.swing.JToggleButton();
        btnDonor = new javax.swing.JToggleButton();
        btnDoctor = new javax.swing.JToggleButton();
        btnNurse = new javax.swing.JToggleButton();
        btnBloodGroup = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 900));
        setMinimumSize(new java.awt.Dimension(1024, 900));
        setResizable(false);

        pnlRoot.setMaximumSize(new java.awt.Dimension(1024, 900));
        pnlRoot.setPreferredSize(new java.awt.Dimension(1024, 900));

        pnlHeader.setBackground(new java.awt.Color(102, 102, 102));
        pnlHeader.setMaximumSize(new java.awt.Dimension(1024, 50));
        pnlHeader.setMinimumSize(new java.awt.Dimension(1024, 50));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/sliit/iblood/assets/Handshake Heart_40px_6.png"))); // NOI18N
        lblTitle.setText(" iBlood");

        lblTimer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTimer.setForeground(new java.awt.Color(255, 255, 255));
        lblTimer.setText(" ");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 669, Short.MAX_VALUE)
                .addComponent(lblTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTimer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        groupMenuButton.add(btnRecipient);
        btnRecipient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRecipient.setText("Recipient");
        btnRecipient.setMaximumSize(new java.awt.Dimension(170, 82));
        btnRecipient.setMinimumSize(new java.awt.Dimension(170, 82));
        btnRecipient.setPreferredSize(new java.awt.Dimension(170, 82));
        btnRecipient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecipientActionPerformed(evt);
            }
        });

        groupMenuButton.add(btnDonation);
        btnDonation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDonation.setText("Donation");
        btnDonation.setMaximumSize(new java.awt.Dimension(170, 82));
        btnDonation.setMinimumSize(new java.awt.Dimension(170, 82));
        btnDonation.setPreferredSize(new java.awt.Dimension(170, 82));
        btnDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonationActionPerformed(evt);
            }
        });

        groupMenuButton.add(btnDonor);
        btnDonor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDonor.setText("Donor");
        btnDonor.setMaximumSize(new java.awt.Dimension(170, 82));
        btnDonor.setMinimumSize(new java.awt.Dimension(170, 82));
        btnDonor.setPreferredSize(new java.awt.Dimension(170, 82));
        btnDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonorActionPerformed(evt);
            }
        });

        groupMenuButton.add(btnDoctor);
        btnDoctor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDoctor.setText("Doctor");
        btnDoctor.setMaximumSize(new java.awt.Dimension(170, 82));
        btnDoctor.setMinimumSize(new java.awt.Dimension(170, 82));
        btnDoctor.setPreferredSize(new java.awt.Dimension(170, 82));
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });

        groupMenuButton.add(btnNurse);
        btnNurse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNurse.setText("Nurse");
        btnNurse.setMaximumSize(new java.awt.Dimension(170, 82));
        btnNurse.setMinimumSize(new java.awt.Dimension(170, 82));
        btnNurse.setPreferredSize(new java.awt.Dimension(170, 82));
        btnNurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNurseActionPerformed(evt);
            }
        });

        groupMenuButton.add(btnBloodGroup);
        btnBloodGroup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBloodGroup.setText("Blood Group");
        btnBloodGroup.setMaximumSize(new java.awt.Dimension(170, 82));
        btnBloodGroup.setMinimumSize(new java.awt.Dimension(170, 82));
        btnBloodGroup.setPreferredSize(new java.awt.Dimension(170, 82));
        btnBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloodGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRootLayout = new javax.swing.GroupLayout(pnlRoot);
        pnlRoot.setLayout(pnlRootLayout);
        pnlRootLayout.setHorizontalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlRootLayout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addGroup(pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDonor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNurse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecipient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDonation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRootLayout.setVerticalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRootLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(btnDonor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnRecipient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnNurse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnDonation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonorActionPerformed
        switchToContent(ContentType.DONOR);
    }//GEN-LAST:event_btnDonorActionPerformed

    private void btnRecipientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecipientActionPerformed
        switchToContent(ContentType.RECIPIENT);
    }//GEN-LAST:event_btnRecipientActionPerformed

    private void btnDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonationActionPerformed
        switchToContent(ContentType.DONATION);
    }//GEN-LAST:event_btnDonationActionPerformed

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        switchToContent(ContentType.DOCTOR);
    }//GEN-LAST:event_btnDoctorActionPerformed

    private void btnNurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNurseActionPerformed
        switchToContent(ContentType.NURSE);
    }//GEN-LAST:event_btnNurseActionPerformed

    private void btnBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloodGroupActionPerformed
        switchToContent(ContentType.BLOOD_TYPE);
    }//GEN-LAST:event_btnBloodGroupActionPerformed

    private enum ContentType {
        DONOR,
        RECIPIENT,
        DONATION,
        DOCTOR,
        NURSE,
        BLOOD_TYPE
    }
}
