/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.sliit.iblood.view_controller;

import sun.security.krb5.internal.tools.Kinit;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * @author pandu
 */
public class MainMenu2 extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDoctor;
    private javax.swing.JToggleButton btnDonation;
    private javax.swing.JToggleButton btnDonor;
    private javax.swing.JToggleButton btnNurse;
    private javax.swing.JToggleButton btnRecipient;
    private javax.swing.JToggleButton btnReport;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel lblTitle;
    private javax.swing.ButtonGroup menuButtonGroup;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMenuBar;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form MainMenu
     */

    public MainMenu2() {

        initComponents();
        initTimer();
        add(new DoctorPanel());
    }

    private void initTimer() {
        final DateFormat timeFormat = new SimpleDateFormat("E, dd MMM yyyy | HH:mm:ss");
        Timer timer = new Timer(1000, e -> {
            Date date = new Date();
            String time = timeFormat.format(date);
            lblTimer.setText(time);
        });
        // to make sure it doesn't wait one second at the start
        timer.setInitialDelay(0);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuButtonGroup = new javax.swing.ButtonGroup();
        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        pnlMenuBar = new javax.swing.JPanel();
        btnDonor = new javax.swing.JToggleButton();
        btnRecipient = new javax.swing.JToggleButton();
        btnDonation = new javax.swing.JToggleButton();
        btnDoctor = new javax.swing.JToggleButton();
        btnNurse = new javax.swing.JToggleButton();
        btnReport = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(1024, 900));
        setPreferredSize(new java.awt.Dimension(1024, 900));

        pnlHeader.setBackground(new java.awt.Color(102, 102, 102));
        pnlHeader.setMaximumSize(new java.awt.Dimension(1024, 50));
        pnlHeader.setMinimumSize(new java.awt.Dimension(1024, 50));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1024, 50));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/sliit/iblood/assets/Handshake Heart_40px_6.png"))); // NOI18N
        lblTitle.setText(" iBlood");

        lblTimer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTimer.setForeground(new java.awt.Color(255, 255, 255));
        lblTimer.setText(" ");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenuBar.setBackground(new java.awt.Color(255, 51, 51));
        pnlMenuBar.setMaximumSize(new java.awt.Dimension(0, 82));
        pnlMenuBar.setMinimumSize(new java.awt.Dimension(0, 82));
        pnlMenuBar.setPreferredSize(new java.awt.Dimension(0, 82));

        menuButtonGroup.add(btnDonor);
        btnDonor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDonor.setText("Donor");
        btnDonor.setMaximumSize(new java.awt.Dimension(170, 82));
        btnDonor.setMinimumSize(new java.awt.Dimension(170, 82));
        btnDonor.setPreferredSize(new java.awt.Dimension(170, 82));
        btnDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonorActionPerformed(evt);
            }
        });

        menuButtonGroup.add(btnRecipient);
        btnRecipient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRecipient.setText("Recipient");
        btnRecipient.setMaximumSize(new java.awt.Dimension(170, 82));
        btnRecipient.setMinimumSize(new java.awt.Dimension(170, 82));
        btnRecipient.setPreferredSize(new java.awt.Dimension(170, 82));
        btnRecipient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecipientActionPerformed(evt);
            }
        });

        menuButtonGroup.add(btnDonation);
        btnDonation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDonation.setText("Donation");
        btnDonation.setMaximumSize(new java.awt.Dimension(170, 82));
        btnDonation.setMinimumSize(new java.awt.Dimension(170, 82));
        btnDonation.setPreferredSize(new java.awt.Dimension(170, 82));
        btnDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonationActionPerformed(evt);
            }
        });

        menuButtonGroup.add(btnDoctor);
        btnDoctor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDoctor.setText("Doctor");
        btnDoctor.setMaximumSize(new java.awt.Dimension(170, 82));
        btnDoctor.setMinimumSize(new java.awt.Dimension(170, 82));
        btnDoctor.setPreferredSize(new java.awt.Dimension(170, 82));
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });

        menuButtonGroup.add(btnNurse);
        btnNurse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNurse.setText("Nurse");
        btnNurse.setMaximumSize(new java.awt.Dimension(170, 82));
        btnNurse.setMinimumSize(new java.awt.Dimension(170, 82));
        btnNurse.setPreferredSize(new java.awt.Dimension(170, 82));
        btnNurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNurseActionPerformed(evt);
            }
        });

        menuButtonGroup.add(btnReport);
        btnReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReport.setText("Report");
        btnReport.setMaximumSize(new java.awt.Dimension(170, 82));
        btnReport.setMinimumSize(new java.awt.Dimension(170, 82));
        btnReport.setPreferredSize(new java.awt.Dimension(170, 82));
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuBarLayout = new javax.swing.GroupLayout(pnlMenuBar);
        pnlMenuBar.setLayout(pnlMenuBarLayout);
        pnlMenuBarLayout.setHorizontalGroup(
            pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBarLayout.createSequentialGroup()
                .addComponent(btnDonor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnRecipient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDonation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnNurse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
        );
        pnlMenuBarLayout.setVerticalGroup(
            pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDonor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRecipient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDonation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnNurse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 768, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoctorActionPerformed

    private void btnDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDonorActionPerformed

    private void btnRecipientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecipientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecipientActionPerformed

    private void btnDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDonationActionPerformed

    private void btnNurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNurseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNurseActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportActionPerformed


}
